### ISSUE TITLE
Problem in run

### ISSUE THREAD

**Issue by thunderZH963** [CMUAbstract/cote#2]
When i try examples, some problems occur.
In bent-pipe, the problem in graph occurs.
but in generate_ecis, run successfully.
Why?
<img width="580" alt="image" src="https://user-images.githubusercontent.com/48862662/100707029-fc192b00-33e4-11eb-975e-b55fa949494b.png">

**Comment by mablem8** [comment]
Looks like you are missing at least one configuration file. The `bent_pipe` example requires the following configuration files:
- `date-time.dat`
- `time-step.dat`
- `num-steps.dat`
- `constellation.dat`
- `*.tle`
- `sensor.dat`
- `tx-*`
- `gnd-*`
- `rx-*`

If you run `prep_bent_pipe_scenarios.sh` in `cote/examples/bent-pipe/scripts/`, it will generate all the files you need - just be sure to specify the sub-directory (e.g. `cote/examples/bent-pipe/configuration/planet-200-ns-20/`) containing the configuration files you want (see `run_bent_pipe_scenarios.sh`).

There is also a helper script, `cote/scripts/generate_small_step_config_files.py`, that generates custom `num-steps.dat` and `time-step.dat` files given a custom TLE file.

**Comment by thunderZH963** [comment]
ok, thanks.
After running, I still have some confused problems about how to understand the meaning of log file and the analysis of running result, some reference documents？

**Comment by mablem8** [comment]
Reference documents are admittedly lacking right now - I can give a summary of the log files for the bent pipe example:
- trigger-time: indicates times at which satellites collect a new image; in this example, all satellites collect a new image at the same moment (different in other examples)
- downlink-Mbps: logs the bit rate of each downlink channel at that time step; in this example, these logs must be cross-referenced with the downlink-tx-rx log (admittedly inconvenient)
- downlink-tx-rx: logs each downlink channel as [sat transmitter id]-[gnd receiver id]
- MB-buffered: logs collected data buffered on each satellite ready for download; data transmitted through a downlink channel reduces this number, and data collected at a trigger time increases this number

**Comment by mablem8** [comment]
Closing since this seems to be resolved
