### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by thunderZH963** [CMUAbstract/cote#3]
some error, 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/48862662/100768842-4e366c80-3436-11eb-9377-d4118e3ffab6.png">
but,
<img width="805" alt="image" src="https://user-images.githubusercontent.com/48862662/100768932-660df080-3436-11eb-81f7-a114410deda7.png">
it's normal.
I want to know why?

**Comment by mablem8** [comment]
Looks like you may have solved it, but for future reference:
`./bent_pipe ../configuration/planet-050-ns-002/ ../logs/planet-050-ns-002/`

**Comment by mablem8** [comment]
`./bent_pipe ../configuration/planet-050-ns-002/ ../logs/` works because `../configuration/planet-050-ns-002/` contains the configuration files, while `../configuration/` does not contain the required configuration files
