### ISSUE TITLE
Some questions about the satellite simulation

### ISSUE THREAD

**Issue by Wang-Ling-jie** [CMUAbstract/cote#7]
I noticed that another repository [oec-asplos20-artifact](https://github.com/CMUAbstract/oec-asplos20-artifact/)  is mentioned in [the Best Paper from ASPLOS'20](https://brandonlucia.com/pubs/oec-asplos2020.pdf), in which there is another implementation of [simulation software](https://github.com/CMUAbstract/oec-asplos20-artifact/tree/master/software) a bit different from this repo, which contains `satsim` and `consim`. What is the functional difference between these two simulation softwares? Is cote in this repo able to simulate  [these different configurations](https://github.com/CMUAbstract/oec-asplos20-artifact/tree/master/artifacts) (i.e. different computing pipeline and power/energe storage configurations)?

**Comment by mablem8** [comment]
This repository contains the canonical version of `cote` and continues to receive updates. For an overview of features, [this presentation](https://leoconn2022.github.io/assets/slides/LEOCONN2022_Bradley_Denby.pdf) might be helpful.

**Comment by Wang-Ling-jie** [comment]
OK, and I want to know how to simulate the different constellation configurations (i.e. fsfp, csfp, fstp and cstp) based on the [all-params.cpp](https://github.com/CMUAbstract/cote/tree/8bd3c46a8406fb11703b23fa33de544cc2483814/examples/all-params), as the original file only simulates the bent-pipe configuration.  It seems that the [constellation configuration file](https://github.com/CMUAbstract/cote/blob/master/examples/all-params/scripts/sample-configuration-files/constellation-0000000001.json) is only loaded but not used in the simulation, can you give me some suggestion on how to use the configuration file to simulate the different constellation configurations?

**Comment by mablem8** [comment]
In the examples directory, there are bent-pipe, close-spaced (cs), and frame-spaced (fs). Frame parallel (fp) vs. tile parallel (tp) is set via data capture quantity in the sensor configuration file (i.e., how many tiles of the frame are retained per sensor capture).

The JSON configuration file you link is an experimental feature that has not been fully implemented; the current version of cote uses individual text files for configuration.
